#!/usr/bin/env python3
"""
AFC-ACE Auto-Detection Utility
Auto-detects ACE Pro devices and generates AFC configuration

Usage:
    python3 detect_ace_devices.py                    # List detected devices
    python3 detect_ace_devices.py --generate-config  # Generate AFC config
"""

import sys
import os
import argparse

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from extras.AFC_ACE_discovery import AceDiscovery
from extras.AFC_ACE_protocol import AceProtocol


def list_devices():
    """List all detected ACE devices"""
    print("Scanning for ACE Pro devices...")
    print()

    devices = AceDiscovery.find_ace_devices()

    if not devices:
        print("No ACE devices found.")
        print()
        print("Troubleshooting:")
        print("  1. Ensure ACE Pro is connected via USB")
        print("  2. Check USB cable is data-capable (not charge-only)")
        print("  3. Verify ACE Pro is powered on")
        print("  4. Check dmesg for USB enumeration errors")
        return

    print(f"Found {len(devices)} ACE device(s):\n")

    for i, device in enumerate(devices):
        print(f"Device {i}:")
        print(f"  Port (tty):      {device.get('port_tty', 'N/A')}")
        print(f"  Port (by-path):  {device.get('port', 'N/A')}")
        print(f"  Device ID:       {device.get('device_id', 'N/A')}")
        print(f"  USB Location:    {device.get('usb_location', 'N/A')}")
        print(f"  Manufacturer:    {device.get('manufacturer', 'N/A')}")
        print(f"  Product:         {device.get('product', 'N/A')}")
        print(f"  Serial Number:   {device.get('serial_number', 'N/A')}")
        print()

        # Try to probe device for firmware info
        try:
            protocol = AceProtocol(device['port'])
            if protocol.connect():
                info = protocol.get_info()
                protocol.disconnect()

                if info:
                    print(f"  Device Info:")
                    print(f"    Model:         {info.get('model', 'Unknown')}")
                    print(f"    Firmware:      {info.get('firmware', 'Unknown')}")
                    print(f"    MAC Address:   {info.get('mac_address', 'N/A')}")
                    print()
        except Exception as e:
            print(f"  (Could not probe device: {e})")
            print()


def generate_config():
    """Generate AFC configuration for detected devices"""
    devices = AceDiscovery.find_ace_devices()

    if not devices:
        print("# No ACE devices found", file=sys.stderr)
        print("# Please connect ACE Pro devices and try again", file=sys.stderr)
        sys.exit(1)

    print("# AFC-ACE Pro Configuration")
    print("# Auto-generated by detect_ace_devices.py")
    print("# Save this to ~/printer_data/config/AFC/AFC_ACE_Pro.cfg")
    print("#")
    print("# This file will be automatically loaded with [include AFC/*.cfg]")
    print("#")
    print("# Each [AFC_lane] includes hub: direct — required so AFC TOOL_LOAD uses the")
    print("# direct-to-toolhead path (ACE has no AFC hub filament sensor).")
    print("# Optional: prep/load MCU pins per lane if you add sensors.")
    print()
    print("# ============================================================")
    print(f"# Found {len(devices)} ACE device(s)")
    print("# ============================================================")
    print()

    for i, device in enumerate(devices):
        unit_name = f"ace{i+1}"
        device_id = device.get('device_id', f'ace_{i}')

        print(f"# ACE Device {i} ({device_id})")
        print(f"# Port: {device.get('port', 'N/A')}")
        print(f"# USB Location: {device.get('usb_location', 'N/A')}")
        print()

        # AFC_ACE unit configuration
        print(f"[AFC_ACE {unit_name}]")
        print(f"serial: {device.get('port', '/dev/ttyACM0')}")
        print("baud: 115200")
        print("# Bowden mm for AFC TOOL_LOAD homing math (hub: direct); tune like [AFC_hub] afc_bowden_length")
        print("# afc_bowden_length: 900")
        print("# afc_unload_bowden_length: 900")
        print("# OR use auto-detection instead of serial:")
        print("# auto_detect: true")
        print(f"# device_index: {i}")
        print()
        print("# Extruder (REQUIRED — change if your [AFC_extruder] name is not 'extruder')")
        print("extruder: extruder")
        print()
        print("# Only set hub: below if you have a real [AFC_hub ...] between ACE and extruder")
        print("# hub: hub")
        print()

        # Generate 4 lanes per ACE device
        for slot in range(4):
            lane_num = i * 4 + slot
            lane_name = f"lane{lane_num + 1}"

            print(f"[AFC_lane {lane_name}]")
            print(f"unit: {unit_name}:{slot}")
            print(f"map: T{lane_num}")
            print("extruder: extruder")
            print("hub: direct")
            print()

        print()

    # Summary
    print("# ============================================================")
    print("# Summary")
    print("# ============================================================")
    print(f"# Total ACE units: {len(devices)}")
    nlanes = len(devices) * 4
    last_t = nlanes - 1
    print(f"# Total lanes: {nlanes} (maps T0-T{last_t})")
    print()
    print("# Next steps:")
    print("# 1. Save this output to ~/printer_data/config/AFC/AFC_ACE_Pro.cfg")
    print("# 2. Remove conflicting BoxTurtle-only AFC unit configs from printer_data if needed")
    print("# 3. Restart Klipper, run PREP, then use T0, T1, ... for tool changes")


def main():
    parser = argparse.ArgumentParser(
        description='AFC-ACE Auto-Detection Utility',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # List detected devices
  python3 detect_ace_devices.py

  # Generate AFC configuration
  python3 detect_ace_devices.py --generate-config

  # Save configuration to file
  python3 detect_ace_devices.py --generate-config > ~/printer_data/config/AFC/AFC_ACE_Pro.cfg
        '''
    )

    parser.add_argument(
        '--generate-config',
        action='store_true',
        help='Generate AFC configuration for detected devices'
    )

    args = parser.parse_args()

    if args.generate_config:
        generate_config()
    else:
        list_devices()


if __name__ == '__main__':
    main()
